name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v2
        id: node_modules_cache_id
        with:
          path: |
            node_modules
          key: node-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Run yarn install
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: Cache workspace
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node-${{ github.sha }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs:
      - setup
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore workspace cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node-${{ github.sha }}
      - name: Run lint
        run: yarn lint
